# Generated by Django 5.1.7 on 2025-04-02 11:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0002_alter_order_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_delivery_time', models.CharField(blank=True, help_text='Contoh: 1-2 hari', max_length=100, null=True)),
                ('method_type', models.CharField(choices=[('standard', 'Standar'), ('express', 'Ekspres'), ('instant', 'Instan'), ('same_day', 'Same Day'), ('next_day', 'Next Day'), ('cargo', 'Cargo')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif')], default='active', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metode Pengiriman',
                'verbose_name_plural': 'Metode Pengiriman',
                'ordering': ['provider__order_sequence', 'provider__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shipping_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif')], default='active', max_length=10)),
                ('tracking_url_format', models.CharField(blank=True, help_text='Format URL untuk tracking (misal: https://cekresi.com/?noresi={tracking_number})', max_length=255, null=True)),
                ('order_sequence', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampilan provider')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Penyedia Pengiriman',
                'verbose_name_plural': 'Penyedia Pengiriman',
                'ordering': ['order_sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pengiriman'), ('processing', 'Sedang Diproses'), ('in_transit', 'Dalam Pengiriman'), ('delivered', 'Terkirim'), ('returned', 'Dikembalikan'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Berat dalam kg', max_digits=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='order.order')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': 'Pengiriman',
                'verbose_name_plural': 'Pengiriman',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Pengiriman'), ('processing', 'Sedang Diproses'), ('in_transit', 'Dalam Pengiriman'), ('delivered', 'Terkirim'), ('returned', 'Dikembalikan'), ('failed', 'Gagal')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Tracking Pengiriman',
                'verbose_name_plural': 'Tracking Pengiriman',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShippingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_order_free_shipping', models.DecimalField(decimal_places=2, default=0.0, help_text='Jumlah minimum order untuk mendapatkan pengiriman gratis (0 untuk menonaktifkan)', max_digits=10)),
                ('flat_shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Biaya pengiriman flat jika tidak menggunakan perhitungan otomatis', max_digits=10)),
                ('use_flat_shipping', models.BooleanField(default=False, help_text='Gunakan biaya pengiriman flat alih-alih perhitungan otomatis')),
                ('default_weight_per_item', models.DecimalField(decimal_places=2, default=0.5, help_text='Berat default per item dalam kg', max_digits=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shipping_config', to='address.city')),
                ('default_origin_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_shipping_config', to='address.province')),
            ],
            options={
                'verbose_name': 'Konfigurasi Pengiriman',
                'verbose_name_plural': 'Konfigurasi Pengiriman',
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingmethod',
            unique_together={('provider', 'code')},
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Harga tambahan per kg jika melebihi min_weight', max_digits=10)),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1)),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to='address.city')),
                ('destination_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_rates', to='address.province')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_rates', to='address.city')),
                ('origin_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_rates', to='address.province')),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
            ],
            options={
                'verbose_name': 'Tarif Pengiriman',
                'verbose_name_plural': 'Tarif Pengiriman',
                'unique_together': {('shipping_method', 'origin_city', 'destination_city', 'min_weight')},
            },
        ),
    ]
