# Generated by Django 5.1.7 on 2025-04-14 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Label/judul alamat', max_length=100)),
                ('address', models.TextField(help_text='Alamat lengkap dalam text')),
                ('note', models.TextField(blank=True, help_text='Catatan tambahan untuk alamat', null=True)),
                ('coordinates', models.CharField(blank=True, help_text='Koordinat lokasi dalam format lat,lng', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alamat',
                'verbose_name_plural': 'Alamat',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
