# Generated by Django 5.1.7 on 2025-04-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address_address_new',
        ),
    ]
