# Generated by Django 5.1.7 on 2025-04-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='user_shipping_address',
        ),
    ]
