# Generated by Django 5.1.7 on 2025-04-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_table'),
    ]

    operations = [
        # Perubahan ini hanya akan memperbarui state migrasi tanpa menyentuh database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='address',
                    name='address_line1',
                    field=models.CharField(blank=True, help_text='Alamat baris 1', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='address_line2',
                    field=models.CharField(blank=True, help_text='Alamat baris 2', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='address_type',
                    field=models.CharField(default='shipping', help_text='Tipe alamat', max_length=20),
                ),
                migrations.AddField(
                    model_name='address',
                    name='city',
                    field=models.CharField(blank=True, help_text='Kota', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='phone_number',
                    field=models.CharField(blank=True, help_text='Nomor telepon penerima', max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='postal_code',
                    field=models.CharField(blank=True, help_text='Kode pos', max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='province',
                    field=models.CharField(blank=True, help_text='Provinsi', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='address',
                    name='recipient_name',
                    field=models.CharField(blank=True, help_text='Nama penerima', max_length=100, null=True),
                ),
            ],
            database_operations=[
                # Tidak ada operasi database, karena kolom-kolom ini sudah ada di database
            ]
        ),
    ]
