# Generated by Django 5.1.7 on 2025-04-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_sync_fields_with_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(default='', help_text='Alamat baris 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(default='', help_text='Alamat baris 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', help_text='Kota', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', help_text='Nomor telepon penerima', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='', help_text='Kode pos', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(default='', help_text='Provinsi', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='recipient_name',
            field=models.CharField(default='', help_text='Nama penerima', max_length=100),
        ),
    ]
