# Generated by Django 5.1.7 on 2025-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ice',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('less', 'Less Ice'), ('no', 'No Ice'), ('hot', 'Hot')], default='normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sugar',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('less', 'Less Sugar'), ('no', 'No Sugar')], default='normal', max_length=20, null=True),
        ),
    ]
