# Generated by Django 5.1.7 on 2025-04-02 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order', 'Pesanan'), ('promo', 'Promosi'), ('info', 'Informasi'), ('payment', 'Pembayaran'), ('system', 'Sistem')], default='info', max_length=10)),
                ('priority', models.CharField(choices=[('high', 'Tinggi'), ('medium', 'Sedang'), ('low', 'Rendah')], default='medium', max_length=10)),
                ('related_url', models.CharField(blank=True, max_length=255, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=36, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_notifications', models.BooleanField(default=True, help_text='Notifikasi terkait pesanan')),
                ('promo_notifications', models.BooleanField(default=True, help_text='Notifikasi promosi dan diskon')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Notifikasi pembayaran')),
                ('system_notifications', models.BooleanField(default=True, help_text='Notifikasi sistem')),
                ('email_notifications', models.BooleanField(default=True, help_text='Kirim notifikasi melalui email')),
                ('push_notifications', models.BooleanField(default=True, help_text='Kirim notifikasi push')),
                ('digest_notifications', models.BooleanField(default=False, help_text='Kirim notifikasi dalam bentuk ringkasan')),
                ('digest_frequency', models.CharField(blank=True, choices=[('daily', 'Harian'), ('weekly', 'Mingguan')], default='daily', max_length=10, null=True)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Waktu mulai jam tenang', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Waktu selesai jam tenang', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Notifikasi',
                'verbose_name_plural': 'Pengaturan Notifikasi',
            },
        ),
    ]
