# Generated by Django 5.1.7 on 2025-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address_text',
            field=models.TextField(blank=True, help_text='Alamat pengiriman dalam format teks', null=True),
        ),
    ]
