# Generated by Django 5.1.7 on 2025-04-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_address_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_text',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
